apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: fleetstore-dsn
  namespace: {{ .Values.platformApi.namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: {{ .Values.platformApi.fleetstore.secretName | default "fleetstore-dsn" }}
    creationPolicy: Owner
  data:
    - secretKey: {{ .Values.platformApi.fleetstore.secretKey | default "dsn" }}
      remoteRef:
        key: {{ .Values.global.cluster_name }}-fleetstore-dsn
