apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.platformApi.app.name }}-mc-config
  namespace: {{ .Values.platformApi.namespace }}
  labels:
    app: {{ .Values.platformApi.app.name }}
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    resourceNames: ["management-clusters"]
    verbs: ["get", "update", "patch"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.platformApi.app.name }}-mc-config
  namespace: {{ .Values.platformApi.namespace }}
  labels:
    app: {{ .Values.platformApi.app.name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Values.platformApi.app.name }}-mc-config
subjects:
  - kind: ServiceAccount
    name: {{ .Values.platformApi.serviceAccount.name }}
    namespace: {{ .Values.platformApi.namespace }}
