dns:
  domain: int0.rosa.devshift.net
  create_environment_zone: true

regional_cluster:
  enable_bastion: true
  enable_cloudtrail: true
  enable_api_custom_domain: true
  node_instance_families: ["m8i", "m7i"]

management_cluster_defaults:
  enable_bastion: true
  node_instance_families: ["m8i", "m7i"]

observability:
  pagerduty:
    enabled: true
