apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-region-env
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  AWS_DEFAULT_REGION: {{ .Values.global.aws_region | quote }}
