apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kube-applier.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kube-applier.labels" . | nindent 4 }}
automountServiceAccountToken: true
