apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: fleetstore-dsn
  namespace: hyperfleet-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: fleetstore-dsn
    creationPolicy: Owner
  data:
    - secretKey: dsn
      remoteRef:
        key: {{ .Values.global.cluster_name }}-fleetstore-dsn
