eksNodePool:
  instanceFamilies:
    - m8i
    - m7i
  capacityType: on-demand
  arch: amd64
  limits:
    cpu: "64"
    memory: 256Gi
  disruption:
    consolidationPolicy: WhenEmpty
    consolidateAfter: 60s
