version: 0.2

env:
  shell: bash

phases:
  build:
    on-failure: RETRY-1
    commands:
      - ./scripts/buildspec/dynamodb-mint.sh

artifacts:
  files:
    - '**/*'
  exclude-paths:
    - '**/.terraform/**'
    - '**/.terraform.lock.hcl'
    - '**/node_modules/**'
