apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: hypershift-config
  namespace: hypershift-install
spec:
  provider: aws
  parameters:
    usePodIdentity: "true"
    region: {{ .Values.hypershift.region | required "region must be set" }}
    objects: |
      - objectName: "hypershift/{{ .Values.global.cluster_name }}-config"
        objectType: "secretsmanager"
        jmesPath:
          - path: "oidcBucketName"
            objectAlias: "oidcBucketName"
          - path: "oidcBucketRegion"
            objectAlias: "oidcBucketRegion"
          - path: "oidcWriterRoleArn"
            objectAlias: "oidcWriterRoleArn"
  secretObjects:
    - secretName: hypershift-config-env
      type: Opaque
      data:
        - objectName: oidcBucketName
          key: OIDC_BUCKET_NAME
        - objectName: oidcBucketRegion
          key: OIDC_BUCKET_REGION
        - objectName: oidcWriterRoleArn
          key: OIDC_WRITER_ROLE_ARN
