# Workaround: The HyperShift operator's default external-dns image pulls from
# registry.redhat.io, which requires a pull secret. Remove this when we no
# longer depend on pull secrets.
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pull-secret
  namespace: hypershift
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-parameter-store
    kind: ClusterSecretStore
  target:
    name: pull-secret
    creationPolicy: Orphan
    template:
      type: kubernetes.io/dockerconfigjson
  data:
    - secretKey: .dockerconfigjson
      remoteRef:
        key: /infra/pull-secret
