{{- if .Values.platform.distributorTargetGroup.arn }}
apiVersion: eks.amazonaws.com/v1
kind: TargetGroupBinding
metadata:
  name: loki-distributor
  namespace: {{ include "loki.namespace" . }}
  labels:
    {{- include "loki.labels" . | nindent 4 }}
  annotations:
    {{- include "loki.annotations" . | nindent 4 }}
spec:
  serviceRef:
    name: {{ .Values.platform.distributorTargetGroup.serviceName | default "loki-distributor" }}
    port: {{ .Values.platform.distributorTargetGroup.port | default 3100 }}
  targetGroupARN: {{ .Values.platform.distributorTargetGroup.arn | quote }}
  targetType: {{ .Values.platform.distributorTargetGroup.targetType | default "ip" }}
{{- end }}
---
{{- if .Values.platform.queryFrontendTargetGroup.arn }}
apiVersion: eks.amazonaws.com/v1
kind: TargetGroupBinding
metadata:
  name: loki-query-frontend
  namespace: {{ include "loki.namespace" . }}
  labels:
    {{- include "loki.labels" . | nindent 4 }}
  annotations:
    {{- include "loki.annotations" . | nindent 4 }}
spec:
  serviceRef:
    name: {{ .Values.platform.queryFrontendTargetGroup.serviceName | default "loki-query-frontend" }}
    port: {{ .Values.platform.queryFrontendTargetGroup.port | default 3100 }}
  targetGroupARN: {{ .Values.platform.queryFrontendTargetGroup.arn | quote }}
  targetType: {{ .Values.platform.queryFrontendTargetGroup.targetType | default "ip" }}
{{- end }}
---
{{- if .Values.platform.sre.targetGroup.arn }}
apiVersion: eks.amazonaws.com/v1
kind: TargetGroupBinding
metadata:
  name: loki-query-frontend-sre
  namespace: {{ include "loki.namespace" . }}
  labels:
    {{- include "loki.labels" . | nindent 4 }}
  annotations:
    {{- include "loki.annotations" . | nindent 4 }}
spec:
  serviceRef:
    name: loki-query-frontend
    port: 3100
  targetGroupARN: {{ .Values.platform.sre.targetGroup.arn | quote }}
  targetType: ip
{{- end }}
