thanos-operator:
  manager:
    args:
      - --leader-elect
      - --metrics-secure
      - --log.format=logfmt
      - --log.level=debug
      - --enable-feature=service-monitor
      - --enable-feature=prometheus-rule
      - --enable-feature=kube-resource-sync
    image:
      repository: quay.io/redhat-user-workloads/rhobs-mco-tenant/rhobs-thanos-operator-main/rhobs-thanos-operator-main
      tag: f83fea08f2a9167647cd8a9fd72f682c638c3cbb
      pullPolicy: IfNotPresent
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        memory: 256Mi